# Generated by Django 3.1.5 on 2021-01-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
        ('posts', '0003_auto_20210113_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='licked',
            field=models.ManyToManyField(blank=True, related_name='liked', to='profiles.Profile'),
        ),
    ]
