# Generated by Django 3.1.5 on 2021-01-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210113_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-create',)},
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
